### ISSUE TITLE
When user click on filter expand and collaspe button, when user navigate to the next tab from the menu, the same expand button is retaining

### ISSUE THREAD

**Issue by jumalekshman** [BharatRajMeriyala/NACHA_Issues#28]
Pending   ODFI Approvals
Pending   RDFI Approvals
Pending   TPSP Approvals
ODFI   Management
RDFI   Management
TPSP   Management
TPS   Management
Pending   TPS Approvals
RDFI   Users
TPSP   Users
TPS   Users

**Comment by BharatRajMeriyala** [comment]
Fixed.

**Comment by 1Tejaswi** [comment]
Working as expected verified in all mentioned screens
