### ISSUE TITLE
TPS Users

### ISSUE THREAD

**Issue by jumalekshman** [BharatRajMeriyala/NACHA_Issues#38]
When user click on Search criteria, and click on search button, user click on the next menu for Eg:, TPSP Users,  same search criteria is retaining

**Comment by BharatRajMeriyala** [comment]
Fixed.

**Comment by 1Tejaswi** [comment]
![filter button conflict](https://user-images.githubusercontent.com/30254361/28404848-8fa0e69a-6d48-11e7-995f-de986733d095.PNG)
![filter button](https://user-images.githubusercontent.com/30254361/28404847-8f9fb20c-6d48-11e7-9d1a-4a1946f2485f.PNG)

**Comment by 1Tejaswi** [comment]
Working as expected
