### ISSUE TITLE
Create TPSP Users

### ISSUE THREAD

**Issue by jumalekshman** [BharatRajMeriyala/NACHA_Issues#49]
Error occurring while saving the create TPSP users

![image](https://user-images.githubusercontent.com/30235753/28330939-04b3db46-6c0d-11e7-8e81-679184617ba7.png)

**Comment by BharatRajMeriyala** [comment]
Fixed.

**Comment by BharatRajMeriyala** [comment]
Fixed.

**Comment by 1Tejaswi** [comment]
Working as expected
