### ISSUE TITLE
Save Button Alignment after error message in TOD Contribution screen

### ISSUE THREAD

**Issue by 1Tejaswi** [BharatRajMeriyala/NACHA_Issues#7]
![save button alignment after error message in tod contribution screen](https://user-images.githubusercontent.com/30254361/28312367-87cda058-6bd0-11e7-9739-d72346f45e0b.png)

**Comment by BharatRajMeriyala** [comment]
This popup is removed.

**Comment by 1Tejaswi** [comment]
Working fine now
